name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v2
      with:
        username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
        password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
        registry: ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io
    - uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/my-image:latest
        secrets: |
          GIT_AUTH_TOKEN=${{ secrets.GIT_AUTH_TOKEN }}

